name: CI Package

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment: gofiber/multi-labeler workflow
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: '.nvmrc'

      - run: npm install
      - run: npm run build
      - run: npm run package
#      - id: app
#        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
#        with:
#          app_id: ${{ secrets.WORKFLOW_APP_ID }}
#          private_key: ${{ secrets.WORKFLOW_PRIVATE_KEY }}

#      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
#        with:
#          token: ${{ steps.app.outputs.token }}
#          commit-message: 'chore(ci): npm run package'
#          title: 'chore(ci): npm run package'
#          body: |
#            #### What this PR does / why we need it:

#            Updated `./dist/**` files with `npm run package`.
#          branch: ci-package
